### ISSUE TITLE
Automate settings checklist for mirrors

### ISSUE THREAD

**Issue by techtonik** [rirror/rirror.github.io#3]
The checklist:

* [x] turn off wiki
* [x] turn off issues
* [x] turn off projects
* [x] add deploy key from sync node (#7)
* [x] set `mirror` topic
---
* [x] update project description with mirror source
* [x] update project url with source code info

**Comment by techtonik** [comment]
Checked points are now listed in https://github.com/rirror/rirror.github.io/blob/master/docs/GITHUB.md
