### ISSUE TITLE
Checklist for adding new projects

### ISSUE THREAD

**Issue by techtonik** [rirror/rirror.github.io#9]
On node side:
* [ ] ...
* [ ] generate deploy key for new project (#8)
* [ ] ...

On GitHub side:
* [ ] add deploy key to new mirror settings
* [ ] commit scripts for new project

**Comment by techtonik** [comment]
Checklist is now here - https://github.com/rirror/rirror.github.io/blob/master/docs/GITHUB.md
